### PR TITLE
teleop rapp implementation

### LINKED ISSUE #199: Generic robot teleop rapp for rocon_apps
I'd like to start a discussion about a generic robot teleop (r)app, which can be used by a variety of robots.

Currently rocon_apps' teleop rapp (https://github.com/robotics-in-concert/rocon_app_platform/blob/hydro-devel/rocon_apps/apps/teleop/teleop.rapp)  is only a virtual rapp. I'd like to turn it into a rapp implementation.

With the capabilities in place - the teleop rapp would depend on the std_capabilities/DifferentialMobileBase' capability (for now) (https://github.com/osrf/std_capabilities/blob/master/interfaces/DifferentialMobileBase.yaml) - it should be feasible to run it on different robots.

@stonier @jihoonl @dwlee @hughie thoughts?

### PR DESCRIPTION
**Pull request by bit-pirate**
So far the teleop rapp has been only a virtual rapp. This PR adds its implementation turning this rapp into an anchestor.

Closes #199

### CODE REVIEW

**Comment by bit-pirate** [comment]
With this in place the `turtlebot_core_apps/teleop` can be removed.

**Comment by bit-pirate** [comment]
Don't merge this yet. More updates are on their way.

**Comment by jihoonl** [comment]
All the topics are globally namespaced. Are they intended?

**Comment by bit-pirate** [comment]
> All the topics are globally namespaced. Are they intended?

That's not an issue any more, since the app  manager and capability server now take care of the remapping. The only part which hasn't been tested is the proper remapping for the concert. To support that, topic relays are no used.

**Comment by jihoonl** [comment]
Is there any discussion thread regarding remapping policy?

**Comment by bit-pirate** [comment]
> Is there any discussion thread regarding remapping policy?

The remapping discussion happened in multiple places with slightly different foci. This issue here is the reminder and I will add details later:

https://github.com/robotics-in-concert/rocon_app_platform/issues/98

**Comment by jihoonl** [comment]
Thanks. I will see this later.

**Comment by stonier** [comment]
> So far the teleop rapp has been only a virtual rapp. This PR adds its implementation turning this rapp into an anchestor.

Correct terminology here would refer to both of these being ancestor rapps (turtle_concert/teleop will be a descendant before and after). The difference being that the former is a _virtual ancestor_ and the latter is not.

**Comment by jihoonl** [comment]
I will reopen PR with updated information.

**Comment by bit-pirate** [comment]
Why do you close this one? Will you use these commits or write everything from scratch?

**Comment by jihoonl** [comment]
I plan to open new PR to indigo branch. I will use these commits.

**Comment by kentsommer** [comment]
:metal:

**Comment by bit-pirate** [comment]
Roger. :+1:

**Pull request closed without merging**
