### PR TITLE
share variable in rapp list file. instead of rapp. 

### PR DESCRIPTION
**Pull request by jihoonl**
https://github.com/robotics-in-concert/rocon_concert/issues/65

Both style are supported for backward compatibility.
- name: rocon_apps/chirp
  share: 10
- rocon_apps/chirp

### CODE REVIEW

**Comment by stonier** [comment]
You're spreading the yaml loading/reading logic over two classes (RappList and Rapp). Can you update to keep the yaml logic in RappList and just load two args into the Rapp constructor (name and share variable)?

**Comment by jihoonl** [comment]
updated.

**Comment by stonier** [comment]
In 4a8b904e57fad60d9550c1637fc8b2ba39722a20 I removed the share: 1 instances, so it illustrates default settings without a share variable.

**Comment by stonier** [comment]
Should we implement the -1 = infinity option?

**Pull request merged**
