### PR TITLE
Notification and handling of malformed rapps

### PR DESCRIPTION
**Pull request by jihoonl**
launch file of rapp is malformed it gives an error, and not include as available rapp. also better explanation why rapp loading failed.

### CODE REVIEW

**Comment by bit-pirate** [comment]
I do not understand the title of this PR :interrobang:

**Comment by jihoonl** [comment]
launch file of rapp is malformed it gives an error, and not include as available rapp.

**Comment by bit-pirate** [comment]
Fix title please.

**Comment by jihoonl** [comment]
done.

**Comment by bit-pirate** [comment]
Looks fine. Merging.

**Pull request merged**
